
# dubbo配置
dubbo:
  application:
    name: springboot-dubbo-provider
  scan:
    base-packages: com.chen.study.dubbo.provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
