
hello:
  format:
    info:
      country: china
      provice: shanghai
      city: shanghai


app:
  datasource:
    db1:
      url: jdbc:mysql://192.168.8.126:3306/db1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      url: jdbc:mysql://192.168.8.126:3306/db1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
